import { RecruiterOutreachService } from './outreach.service';
import { createTransport } from 'nodemailer';
import { OrgContext } from '../common/org-context';
jest.mock('nodemailer',()=>({createTransport:jest.fn()}));
const ctx={organisationId:'org-a',userId:'member-a',permissions:['messages.use','candidates.read','candidates.resume.view']} as OrgContext;
function setup(){const prisma:any={candidate:{findMany:jest.fn().mockResolvedValue([{id:'c1',firstName:'A',lastName:'One',email:'a@example.com',professional:{searchDetails:{}}}])},tokenTransaction:{findMany:jest.fn().mockResolvedValue([{idempotencyKey:'resume:c1'}])},recruiterEmailBatch:{findFirst:jest.fn(),findUnique:jest.fn().mockResolvedValue(null),create:jest.fn().mockResolvedValue({id:'batch'})},recruiterEmailRecipient:{updateMany:jest.fn().mockResolvedValue({count:1})}};const config={get:(key:string)=>({RECRUITER_SMTP_HOST:'smtp.example.test',RECRUITER_EMAIL_FROM:'sender@example.test'}[key])};const service=new RecruiterOutreachService(prisma,config as never);return{prisma,service};}
const snapshot={id:'batch',subject:'Opportunity',body:'A role to discuss',configured:true,pending:1,recipients:[{candidateId:'c1',name:'A One',status:'PENDING',detail:null}]};
afterEach(()=>jest.clearAllMocks());
describe('Recruiter email boundaries and delivery state',()=>{
 it('requires contact permission even for previews',async()=>{const{service,prisma}=setup();await expect(service.preview({...ctx,permissions:['messages.use']},{requestId:'r',candidateIds:['c1'],subject:'Hi',body:'Hello'})).rejects.toThrow('candidates.read');expect(prisma.candidate.findMany).not.toHaveBeenCalled();});
 it('skips locked and opted-out recipients without exposing email addresses',async()=>{const{service,prisma}=setup();prisma.tokenTransaction.findMany.mockResolvedValue([]);jest.spyOn(service,'status').mockResolvedValue({...snapshot,pending:0});await service.preview(ctx,{requestId:'r',candidateIds:['c1'],subject:'Hi',body:'Hello'});expect(prisma.recruiterEmailBatch.create.mock.calls[0][0].data.recipients.create[0]).toEqual({candidateId:'c1',status:'SKIPPED',detail:'Contact locked'});expect(createTransport).not.toHaveBeenCalled();});
 it('rejects cross-tenant candidates before creating any batch',async()=>{const{service,prisma}=setup();await expect(service.preview(ctx,{requestId:'r',candidateIds:['c1','other-org'],subject:'Hi',body:'Hello'})).rejects.toThrow('unavailable');expect(prisma.recruiterEmailBatch.create).not.toHaveBeenCalled();});
 it('does not send twice when another request has claimed a recipient',async()=>{const{service,prisma}=setup();jest.spyOn(service,'status').mockResolvedValue(snapshot);prisma.recruiterEmailRecipient.updateMany.mockResolvedValue({count:0});const sendMail=jest.fn(),close=jest.fn();(createTransport as jest.Mock).mockReturnValue({sendMail,close});await service.dispatch(ctx,'batch');expect(sendMail).not.toHaveBeenCalled();expect(close).toHaveBeenCalled();});
 it('marks SMTP timeouts uncertain instead of retrying or reporting success',async()=>{const{service,prisma}=setup();jest.spyOn(service,'status').mockResolvedValue(snapshot);const sendMail=jest.fn().mockRejectedValue(new Error('timeout'));(createTransport as jest.Mock).mockReturnValue({sendMail,close:jest.fn()});await service.dispatch(ctx,'batch');expect(sendMail).toHaveBeenCalledTimes(1);expect(prisma.recruiterEmailRecipient.updateMany).toHaveBeenLastCalledWith(expect.objectContaining({data:expect.objectContaining({status:'UNCERTAIN'})}));});
});
