// ============================================================
// DEVELOPMENT ONLY MOCK LAYER
// Purpose:
// Provides realistic development fallback data conforming to the backend
// contract when the live NestJS backend is unreachable or during UI previews.
// ============================================================

import {
  PlatformDashboardSummary,
  Organisation,
  PlatformAdminUser,
  TokenPlan,
  TokenTransaction,
  AuditLogItem,
  SecurityEvent,
  PlatformSetting,
} from '../types/platform.types';

export const mockOrganisations: Organisation[] = [
  {
    id: 'org_acme_corp',
    name: 'Acme Corporation',
    slug: 'acme-corp',
    domain: 'acme.com',
    contactEmail: 'talent@acme.com',
    contactPhone: '+1 (555) 234-5678',
    status: 'ACTIVE',
    tier: 'ENTERPRISE',
    maxRecruiters: 25,
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-09-20T14:10:00Z',
    membersCount: 18,
    tokenBalance: 8500,
    allocatedTokens: 12000,
    consumedTokens: 3500,
    industry: 'Enterprise Software & Cloud',
    companySize: '500-1000',
    website: 'https://acme.com',
  },
  {
    id: 'org_stellar_ai',
    name: 'Stellar AI Labs',
    slug: 'stellar-ai',
    domain: 'stellarai.io',
    contactEmail: 'people@stellarai.io',
    contactPhone: '+1 (555) 890-1234',
    status: 'ACTIVE',
    tier: 'GROWTH',
    maxRecruiters: 10,
    createdAt: '2026-03-10T11:00:00Z',
    updatedAt: '2026-09-24T16:45:00Z',
    membersCount: 8,
    tokenBalance: 4200,
    allocatedTokens: 5000,
    consumedTokens: 800,
    industry: 'Artificial Intelligence',
    companySize: '50-200',
    website: 'https://stellarai.io',
  },
  {
    id: 'org_nexus_health',
    name: 'Nexus Health Systems',
    slug: 'nexus-health',
    domain: 'nexushealth.org',
    contactEmail: 'hr@nexushealth.org',
    contactPhone: '+1 (555) 432-8765',
    status: 'SUSPENDED',
    suspensionReason: 'Breach of candidate data usage policy section 4.2 pending compliance audit',
    suspendedAt: '2026-09-18T10:15:00Z',
    tier: 'STANDARD',
    maxRecruiters: 5,
    createdAt: '2026-04-05T08:00:00Z',
    updatedAt: '2026-09-18T10:15:00Z',
    membersCount: 3,
    tokenBalance: 950,
    allocatedTokens: 2000,
    consumedTokens: 1050,
    industry: 'Healthcare Technology',
    companySize: '200-500',
    website: 'https://nexushealth.org',
  },
  {
    id: 'org_finflow_tech',
    name: 'FinFlow Technologies',
    slug: 'finflow-tech',
    domain: 'finflow.co',
    contactEmail: 'recruiting@finflow.co',
    status: 'PENDING_VERIFICATION',
    tier: 'STANDARD',
    maxRecruiters: 5,
    createdAt: '2026-09-27T18:20:00Z',
    updatedAt: '2026-09-27T18:20:00Z',
    membersCount: 1,
    tokenBalance: 0,
    allocatedTokens: 0,
    consumedTokens: 0,
    industry: 'Fintech & Payments',
    companySize: '10-50',
    website: 'https://finflow.co',
  },
];

export const mockAdmins: PlatformAdminUser[] = [
  {
    id: 'usr_super_1',
    email: 'superadmin@clyptus.platform',
    firstName: 'Devendra',
    lastName: 'Vance',
    role: 'PLATFORM_SUPER_ADMIN',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    platformAdminProfile: {
      department: 'Platform Architecture',
      permissions: ['*'],
      isActive: true,
    },
  },
  {
    id: 'usr_admin_ops_1',
    email: 'sarah.ops@clyptus.platform',
    firstName: 'Sarah',
    lastName: 'Connor',
    role: 'PLATFORM_ADMIN',
    isActive: true,
    createdAt: '2026-02-14T10:00:00Z',
    platformAdminProfile: {
      department: 'Operations & Compliance',
      permissions: [
        'platform.organisations.read',
        'platform.organisations.update',
        'platform.organisations.suspend',
        'platform.audit.read',
      ],
      isActive: true,
    },
  },
  {
    id: 'usr_admin_billing_1',
    email: 'marcus.tokens@clyptus.platform',
    firstName: 'Marcus',
    lastName: 'Brody',
    role: 'PLATFORM_ADMIN',
    isActive: false,
    createdAt: '2026-04-12T14:30:00Z',
    platformAdminProfile: {
      department: 'Token & Billing Oversight',
      permissions: [
        'platform.tokens.read',
        'platform.tokens.manage',
        'platform.tokens.adjust',
      ],
      isActive: false,
    },
  },
];

export const mockTokenPlans: TokenPlan[] = [
  {
    id: 'plan_starter',
    name: 'Starter Plan',
    code: 'PLAN_STARTER',
    description: 'Designed for small teams and emerging startups.',
    tokenAmount: 1000,
    priceCents: 9900,
    currency: 'USD',
    billingCycle: 'MONTHLY',
    features: ['5 Active Job Posts', 'Resume Parsing', 'Basic Support'],
    isActive: true,
    sortOrder: 1,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'plan_growth',
    name: 'Growth Plan',
    code: 'PLAN_GROWTH',
    description: 'Scaling recruitment workflows with AI matching and ATS.',
    tokenAmount: 5000,
    priceCents: 39900,
    currency: 'USD',
    billingCycle: 'MONTHLY',
    features: ['Unlimited Job Posts', 'AI Candidate Matching', 'ATS Integration', 'Priority Support'],
    isActive: true,
    sortOrder: 2,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'plan_enterprise',
    name: 'Enterprise Scale',
    code: 'PLAN_ENTERPRISE',
    description: 'Dedicated volume allocations and custom integration support.',
    tokenAmount: 25000,
    priceCents: 149900,
    currency: 'USD',
    billingCycle: 'ANNUAL',
    features: ['Custom Token Allocation', 'Dedicated Account Manager', 'Custom Workflows', 'SSO & Audit Export'],
    isActive: true,
    sortOrder: 3,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const mockTokenTransactions: TokenTransaction[] = [
  {
    id: 'tx_991823',
    organisationId: 'org_acme_corp',
    organisationName: 'Acme Corporation',
    organisationSlug: 'acme-corp',
    type: 'ALLOCATION',
    amount: 5000,
    balanceBefore: 3500,
    balanceAfter: 8500,
    reason: 'Enterprise annual quota allocation',
    referenceId: 'order_ent_2026_09',
    createdAt: '2026-09-27T10:14:00Z',
  },
  {
    id: 'tx_991811',
    organisationId: 'org_stellar_ai',
    organisationName: 'Stellar AI Labs',
    organisationSlug: 'stellar-ai',
    type: 'CONSUMPTION',
    amount: -300,
    balanceBefore: 4500,
    balanceAfter: 4200,
    reason: 'Bulk candidate AI match execution (60 candidates)',
    referenceId: 'batch_match_491',
    createdAt: '2026-09-26T16:22:00Z',
  },
  {
    id: 'tx_991789',
    organisationId: 'org_nexus_health',
    organisationName: 'Nexus Health Systems',
    organisationSlug: 'nexus-health',
    type: 'REFUND',
    amount: 150,
    balanceBefore: 800,
    balanceAfter: 950,
    reason: 'Job post cancellation refund by platform admin',
    referenceId: 'refund_ref_882',
    createdAt: '2026-09-25T11:05:00Z',
  },
];

export const mockAuditLogs: AuditLogItem[] = [
  {
    id: 'aud_8892',
    actorId: 'usr_super_1',
    actorRole: 'PLATFORM_SUPER_ADMIN',
    action: 'ORGANISATION_SUSPENDED',
    entityType: 'ORGANISATION',
    entityId: 'org_nexus_health',
    organisationId: 'org_nexus_health',
    organisationName: 'Nexus Health Systems',
    metadata: { reason: 'Breach of candidate data usage policy section 4.2' },
    ipAddress: '192.168.1.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    createdAt: '2026-09-18T10:15:00Z',
    actor: { firstName: 'Devendra', lastName: 'Vance', email: 'superadmin@clyptus.platform' },
  },
  {
    id: 'aud_8891',
    actorId: 'usr_super_1',
    actorRole: 'PLATFORM_SUPER_ADMIN',
    action: 'TOKEN_ADJUSTMENT_EXECUTED',
    entityType: 'TOKEN_LEDGER',
    entityId: 'tx_991823',
    organisationId: 'org_acme_corp',
    organisationName: 'Acme Corporation',
    metadata: { amount: 5000, type: 'ALLOCATION' },
    ipAddress: '192.168.1.45',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    createdAt: '2026-09-27T10:14:00Z',
    actor: { firstName: 'Devendra', lastName: 'Vance', email: 'superadmin@clyptus.platform' },
  },
  {
    id: 'aud_8889',
    actorId: 'usr_admin_ops_1',
    actorRole: 'PLATFORM_ADMIN',
    action: 'ORGANISATION_UPDATED',
    entityType: 'ORGANISATION',
    entityId: 'org_stellar_ai',
    organisationId: 'org_stellar_ai',
    organisationName: 'Stellar AI Labs',
    metadata: { updatedFields: ['tier', 'maxRecruiters'] },
    ipAddress: '10.0.0.12',
    createdAt: '2026-09-24T16:45:00Z',
    actor: { firstName: 'Sarah', lastName: 'Connor', email: 'sarah.ops@clyptus.platform' },
  },
];

export const mockSecurityEvents: SecurityEvent[] = [
  {
    id: 'sec_1092',
    eventType: 'AUTH_FAILED_EXCESSIVE_ATTEMPTS',
    severity: 'HIGH',
    ipAddress: '198.51.100.24',
    userAgent: 'Python-requests/2.28',
    details: { attempts: 12, targetEmail: 'admin@clyptus.platform' },
    isResolved: false,
    createdAt: '2026-09-28T08:12:00Z',
  },
  {
    id: 'sec_1088',
    eventType: 'TOKEN_EXPIRATION_ALERT',
    severity: 'LOW',
    ipAddress: '127.0.0.1',
    details: { expiredTokenCount: 1500, organisationsAffected: 2 },
    isResolved: true,
    resolvedAt: '2026-09-27T12:00:00Z',
    resolutionNotes: 'Standard ledger expiration worker successfully closed out cycle.',
    createdAt: '2026-09-27T00:01:00Z',
  },
];

export const mockSettings: PlatformSetting[] = [
  {
    id: 'set_1',
    key: 'PLATFORM_NAME',
    value: 'Clyptus Recruitment Platform',
    category: 'GENERAL',
    description: 'Global name of the recruitment platform displayed to all portals',
    isEncrypted: false,
    isPublic: true,
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'set_2',
    key: 'SECURITY_MFA_ENFORCED',
    value: true,
    category: 'SECURITY',
    description: 'Enforces hardware or TOTP 2FA across all Platform Super Admins and Admins',
    isEncrypted: false,
    isPublic: false,
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'set_3',
    key: 'TOKEN_DEFAULT_EXPIRY_DAYS',
    value: 365,
    category: 'BILLING',
    description: 'Ledger lifetime in days before unused purchased tokens expire',
    isEncrypted: false,
    isPublic: false,
    updatedAt: '2026-09-15T12:00:00Z',
  },
  {
    id: 'set_4',
    key: 'INTEGRATION_RAZORPAY_ACTIVE',
    value: true,
    category: 'INTEGRATION',
    description: 'Enables Razorpay payment processing gateway for token purchases',
    isEncrypted: false,
    isPublic: false,
    updatedAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'set_5',
    key: 'INTEGRATION_STRIPE_ACTIVE',
    value: true,
    category: 'INTEGRATION',
    description: 'Enables Stripe payment processing gateway for international enterprise invoices',
    isEncrypted: false,
    isPublic: false,
    updatedAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'set_6',
    key: 'INTEGRATION_OPEN_SEARCH_SYNC',
    value: true,
    category: 'INTEGRATION',
    description: 'Real-time asynchronous index synchronization with OpenSearch',
    isEncrypted: false,
    isPublic: false,
    updatedAt: '2026-09-22T09:30:00Z',
  },
];

export const mockDashboardSummary: PlatformDashboardSummary = {
  metrics: {
    totalOrganisations: 4,
    activeOrganisations: 2,
    suspendedOrganisations: 1,
    pendingOrganisations: 1,
    totalPlatformUsers: 1420,
    totalPlatformAdmins: 3,
    tokenMetrics: {
      totalActiveTokens: 13650,
      totalAllocatedTokens: 19000,
      totalConsumedTokens: 5350,
    },
  },
  recentOrganisations: mockOrganisations,
  recentTransactions: mockTokenTransactions,
  recentSecurityEvents: mockSecurityEvents,
  recentAuditLogs: mockAuditLogs,
  systemHealth: {
    status: 'HEALTHY',
    timestamp: new Date().toISOString(),
    uptimeSeconds: 86420,
    services: {
      database: { status: 'UP', latencyMs: 2 },
      redis: { status: 'UP', latencyMs: 1 },
      storage: { status: 'UP' },
      paymentGateways: { status: 'UP' },
      search: { status: 'UP' },
    },
  },
};
